2021-11-24 22:02:04,baseAPI(line:73),ERROR|Traceback (most recent call last):
  File "G:\SongQin\Python\Demo\Delivery_System_1108\common\baseAPI.py", line 67, in request_send
    print(xintian)
NameError: name 'xintian' is not defined

